const projects=[
 {year:'2026',tag:'Deployment · Training · Support',title:'BWTD — Nationwide Deployment',org:'Jabatan Akauntan Negara Malaysia',desc:'Coordinated nationwide deployment activities, sourcing, logistics, travel planning and cost estimation. Delivered end-user training and supported software updates and patch deployments.',impact:['Nationwide coordination','End-user training','Patch deployment']},
 {year:'2025',tag:'Python · Data · Secure Production',title:'Kad Kuasa Staf',org:'Jabatan Pendaftaran Negara',desc:'Managed the workflow from data preparation through card production and delivery. Cleaned and validated records, configured HID templates, and built Python automation for image retrieval and QR generation.',impact:['Python automation','Data validation','Production & QC']},
 {year:'2025',tag:'IT Support · Maintenance · Training',title:'Malaysia–Thailand Border Pass',org:'Imigresen Malaysia',desc:'Supported systems and devices across multiple sites, coordinated hardware supply, system setup, troubleshooting, maintenance and operator training.',impact:['Multi-site support','Device configuration','User consultation']},
 {year:'2024',tag:'QA · Logistics · Operations',title:'Pemacu Pena SPM',org:'Lembaga Peperiksaan',desc:'Supported production and nationwide distribution of USB media for SPM hearing examinations, including data loading, QA, functionality testing, packaging and secure delivery.',impact:['Quality assurance','Secure delivery','Technical testing']}
]
const skills=['IT Support & Troubleshooting','Technical Project Coordination','Nationwide Deployment','Python Automation','Data Cleaning & Validation','Excel & Reporting','Hardware / Software Support','End-user Training','Vendor & Client Coordination','Quality Control','Technical Documentation','Web Development']
const whatsapp='https://wa.me/60198786832?text=Hi%20Adli%2C%20I%20came%20across%20your%20portfolio%20and%20would%20like%20to%20get%20in%20touch.'
export default function Home(){return <main>
<nav><a className="brand" href="#top">AJ<span>.</span></a><div className="links"><a href="#about">About</a><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#contact">Contact</a></div><a className="mini" href="/Adli-Jabir-Resume.pdf" target="_blank">Résumé ↗</a></nav>
<section className="hero" id="top"><div className="heroGrid"><div><div className="eyebrow">AVAILABLE FOR IT & TECHNICAL PROJECT OPPORTUNITIES</div><h1>IT operations.<br/><em>Projects delivered.</em><br/>Work automated.</h1><p className="lead">I’m <b>Adli Jabir</b>, an IT Executive and Technical Project Coordinator experienced in multi-site support, government project deployment, data operations and Python automation.</p><div className="actions"><a className="primary" href="#projects">Explore my work ↓</a><a className="whatsapp" href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp me ↗</a><a className="secondary" href="/Adli-Jabir-Resume.pdf" target="_blank">View résumé</a></div></div><div className="portraitWrap"><div className="portraitCard"><img src="/profile.png" alt="Adli Jabir" className="profilePhoto"/></div><div className="portraitCaption"><strong>Adli Jabir</strong><span>IT Executive · Technical Project Coordinator</span><a href={whatsapp} target="_blank" rel="noopener noreferrer">019-878 6832 · WhatsApp ↗</a></div></div></div><div className="stats"><div><strong>2024—Now</strong><span>IT Executive</span></div><div><strong>Nationwide</strong><span>Project deployments</span></div><div><strong>Python</strong><span>Workflow automation</span></div></div></section>
<section id="about" className="split"><div><p className="sectionNo">01 / ABOUT</p><h2>Technical execution meets <em>project coordination.</em></h2></div><div className="copy"><p>I work across the full operational lifecycle: preparing data, configuring systems and devices, troubleshooting issues, coordinating engineers and vendors, planning deployments, training users and reporting progress to stakeholders.</p><p>My background in Computer Science helps me go beyond day-to-day support. I use automation and structured data workflows to make operational processes faster, more consistent and easier to manage.</p></div></section>
<section className="skills"><p className="sectionNo">CORE CAPABILITIES</p><div className="skillgrid">{skills.map((s,i)=><div className="skill" key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}</div>)}</div></section>
<section id="projects"><div className="heading"><div><p className="sectionNo">02 / SELECTED WORK</p><h2>Projects with <em>real operations</em> behind them.</h2></div><p>Selected work involving nationwide deployment, secure production, technical support and automation.</p></div><div className="projects">{projects.map((p,i)=><article className="project" key={p.title}><div className="pnum">0{i+1}</div><div className="projectbody"><div className="meta"><span>{p.year}</span><span>{p.tag}</span></div><h3>{p.title}</h3><h4>{p.org}</h4><p>{p.desc}</p><div className="chips">{p.impact.map(x=><span key={x}>{x}</span>)}</div></div></article>)}</div></section>
<section id="experience" className="experience"><p className="sectionNo">03 / EXPERIENCE</p><div className="job"><div><span>2024 — PRESENT</span><h3>IT Executive</h3><p>Sysbot Resource Sdn. Bhd.</p></div><div><p>Multi-site IT operations, government project coordination, deployment planning, technical support, maintenance, Python automation, data preparation, secure production, training and stakeholder reporting.</p></div></div><div className="job"><div><span>2022</span><h3>E-Commerce & Marketing Intern</h3><p>Zeto Travel Sdn. Bhd.</p></div><div><p>Product listings, promotional materials, production database support, inventory updates, order processing, customer support and market research.</p></div></div></section>
<section className="education"><div><p className="sectionNo">04 / EDUCATION</p><h2>Bachelor of Computer Science<br/><em>Minor in Mathematics</em></h2><p>Universiti Sains Malaysia · 2023</p></div><div className="credential"><span>CERTIFICATION</span><h3>Kaseya Certified<br/>Technology Specialist</h3><p>KCTS</p></div></section>
<section id="contact" className="contact"><p className="sectionNo">05 / CONTACT</p><h2>Have a technical challenge<br/>or project to <em>deliver?</em></h2><p>I'm open to opportunities in IT support, technical operations, project coordination, system deployment and automation.</p><div className="contactDetails"><div><span>EMAIL</span><a href="mailto:adli.fx00@gmail.com">adli.fx00@gmail.com</a></div><div><span>PHONE / WHATSAPP</span><a href={whatsapp} target="_blank" rel="noopener noreferrer">019-878 6832 ↗</a></div></div><div className="actions"><a className="primary" href={whatsapp} target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a><a className="secondary light" href="/Adli-Jabir-Resume.pdf" target="_blank">Download résumé</a></div></section>
<footer><a className="brand" href="#top">AJ<span>.</span></a><span>Adli Jabir · IT Executive</span><span>Portfolio · 2026</span></footer>
</main>}
