const whatsapp = "https://wa.me/60198786832?text=Hi%20Adli%2C%20I%20came%20across%20your%20portfolio%20and%20would%20like%20to%20get%20in%20touch.";
const projects = [
  {year:"2026",title:"Nationwide System Deployment and User Training",client:"Jabatan Akauntan Negara Malaysia",category:"Deployment / Training",description:"Coordinated equipment and system deployment across multiple locations, matching site requirements to available resources.",details:["Prepared deployment schedules, travel plans and cost estimates.","Trained end users on software and system operation.","Supported software updates, patch deployment and issue resolution."]},
  {year:"2025",title:"Data Automation and Production Support",client:"Jabatan Pendaftaran Negara Malaysia",category:"Python / Excel / Quality",description:"Supported the workflow from client data preparation and validation through production, quality checks and delivery.",details:["Cleaned and consolidated records in Excel.","Developed Python scripts for image downloads and QR code generation.","Configured production templates and checked output accuracy."]},
  {year:"2025",title:"Multi Site Technical Support and Operations",client:"Jabatan Imigresen Malaysia",category:"IT Support / Maintenance",description:"Provided technical support and system maintenance across client sites, coordinating with internal teams and external partners.",details:["Assisted with device setup, troubleshooting and maintenance checks.","Coordinated project materials and supporting hardware.","Provided on-site user training and progress reporting."]},
  {year:"2024",title:"Digital Content Preparation and Distribution",client:"Lembaga Peperiksaan Malaysia",category:"Quality / Logistics",description:"Supported production, content loading and quality assurance for a nationwide distribution project.",details:["Checked completeness, functionality, compatibility and playback.","Coordinated packaging, labelling and delivery.","Maintained project documentation and status updates."]}
];
const skills = [
  "Hardware & software troubleshooting","Device configuration","System maintenance",
  "Software updates & patch deployment","Nationwide deployments","User training",
  "Vendor & technician coordination","Travel planning & cost estimation","Microsoft Excel",
  "Data cleaning & validation","Python automation","QR code generation",
  "Production software & templates","Quality checks","Technical documentation",
  "Management reporting"
];
export default function Home(){
 return <main id="top">
  <nav className="nav"><a className="brand" href="#top">AJ<span>.</span></a><div className="navLinks"><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#contact">Contact</a></div><a className="navResume" href="/Adli-Jabir-Resume.pdf" target="_blank" rel="noopener noreferrer">Résumé ↗</a></nav>
  <section className="hero">
   <div className="heroGrid"><div className="heroCopy">
    <p className="eyebrow">IT EXECUTIVE · TECHNICAL SUPPORT · DEPLOYMENT COORDINATION</p>
    <h1>Supporting systems.<br/><em>Coordinating rollouts.</em><br/>Solving problems.</h1>
    <p className="lead">Hi, I’m <strong>Adli Jabir.</strong> I support hardware, software and users across multiple sites nationwide—combining hands-on troubleshooting, deployment coordination, user training, Excel data validation and Python automation.</p>
    <div className="actions"><a className="primary" href="#projects">Explore my work ↓</a><a className="whatsapp" href={whatsapp} target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a><a className="secondary" href="/Adli-Jabir-Resume.pdf" target="_blank" rel="noopener noreferrer">View résumé</a></div>
   </div><div className="portraitWrap"><div className="portraitCard"><img src="/profile.png" alt="Portrait of Adli Jabir" className="profilePhoto"/></div><div className="portraitCaption"><strong>Adli Jabir</strong><span>IT Executive · Technical Support</span><a href={whatsapp} target="_blank" rel="noopener noreferrer">+60 19-878 6832 · WhatsApp ↗</a></div></div></div>
   <div className="stats"><div><strong>2024—Present</strong><span>IT Executive</span></div><div><strong>Nationwide</strong><span>Multi-site support & deployments</span></div><div><strong>Excel + Python</strong><span>Data preparation & automation</span></div></div>
  </section>
  <section id="about" className="about split"><div><p className="sectionNo">01 / ABOUT</p><h2>Technical support meets <em>operational delivery.</em></h2></div><div className="aboutText"><p>I work with clients, vendors, engineers and internal teams to maintain day-to-day operations and deliver system rollouts. My work covers troubleshooting, device setup, maintenance, logistics, user handovers and reporting.</p><p>I also prepare and validate datasets in Excel and develop Python scripts to make repeatable production tasks more consistent.</p></div></section>
  <section id="skills" className="skills"><p className="sectionNo">02 / CORE SKILLS</p><h2>Tools and capabilities I use.</h2><div className="skillGrid">{skills.map((skill,i)=><div className="skill" key={skill}><span>{String(i+1).padStart(2,"0")}</span>{skill}</div>)}</div></section>
  <section id="projects" className="projectsSection"><div className="sectionHeading"><div><p className="sectionNo">03 / SELECTED PROJECT EXPERIENCE</p><h2>Work across <em>multiple sites and teams.</em></h2></div><p>Project descriptions use the broader titles and agency names from my updated résumé.</p></div><div className="projects">{projects.map((p,i)=><article className="project" key={p.title}><span className="projectNum">0{i+1}</span><div><div className="meta"><span>{p.year}</span><span>{p.category}</span></div><h3>{p.title}</h3><h4>{p.client}</h4><p>{p.description}</p><ul>{p.details.map(d=><li key={d}>{d}</li>)}</ul></div></article>)}</div></section>
  <section id="experience" className="experience"><p className="sectionNo">04 / PROFESSIONAL EXPERIENCE</p><div className="job"><div><span className="date">2024 — PRESENT</span><h3>IT Executive</h3><p>Sysbot Resource Sdn. Bhd.</p></div><div><p>Provide hardware and software support to internal departments and client sites. Coordinate nationwide deployments, technician allocation, sourcing, logistics, travel and cost estimates. Conduct training, maintain systems, validate Excel datasets, automate image and QR workflows in Python, and prepare technical and management reports.</p></div></div><div className="job"><div><span className="date">2022</span><h3>E-commerce and Marketing Intern</h3><p>Zeto Travel Sdn. Bhd.</p></div><div><p>Created Shopee and Lazada listings and Canva promotional materials. Assisted with production database setup, inventory, order processing, customer enquiries and market research.</p></div></div></section>
  <section className="education"><div><p className="sectionNo">05 / EDUCATION</p><h2>Bachelor of Computer Science<br/><em>Minor in Mathematics</em></h2><p>Universiti Sains Malaysia, Penang · 2023</p><p>Science Stream · Kolej Matrikulasi Selangor, Banting · 2019</p></div><div className="credential"><span>CERTIFICATION</span><h3>Kaseya Certified Technology Specialist</h3><p>KCTS</p></div></section>
  <section id="contact" className="contact"><p className="sectionNo">06 / CONTACT</p><h2>Need IT support or help<br/>delivering a <em>rollout?</em></h2><p>I’m open to conversations about IT support, technical operations, deployment coordination and data automation.</p><div className="contactDetails"><div><span>EMAIL</span><a href="mailto:adli.fx00@gmail.com">adli.fx00@gmail.com</a></div><div><span>PHONE / WHATSAPP</span><a href={whatsapp} target="_blank" rel="noopener noreferrer">+60 19-878 6832 ↗</a></div></div><div className="actions"><a className="primary" href={whatsapp} target="_blank" rel="noopener noreferrer">Message me on WhatsApp ↗</a><a className="secondary light" href="/Adli-Jabir-Resume.pdf" target="_blank" rel="noopener noreferrer">Download résumé</a></div></section>
  <footer><a className="brand" href="#top">AJ<span>.</span></a><span>Adli Jabir · IT Executive</span><span>Portfolio · 2026</span></footer>
 </main>
}
